name: ESLint Check

on:
  pull_request:
    branches: [ mai, dev ]
    paths:
      - 'client/**/*.ts'
      - 'client/**/*.tsx'
      - '.github/workflows/eslint-check.yml'
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Set this to your Node.js version

    - name: Change to client directory
      run: cd client

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint '**/*.{ts,tsx}' --quiet

    - name: Check for TypeScript errors
      run: npx tsc --noEmit
